/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'inverse-primary': '#bec6e0',
        'secondary-fixed': '#d5e3fd',
        'on-secondary-container': '#57657b',
        'surface-container-lowest': '#ffffff',
        'secondary': '#515f74',
        'primary-fixed': '#dae2fd',
        'error-container': '#ffdad6',
        'surface-variant': '#e0e3e5',
        'inverse-on-surface': '#eff1f3',
        'on-background': '#191c1e',
        'outline': '#76777d',
        'surface-dim': '#d8dadc',
        'primary': '#000000',
        'surface-container': '#eceef0',
        'on-tertiary-fixed': '#001f26',
        'on-primary-fixed-variant': '#3f465c',
        'primary-container': '#131b2e',
        'on-secondary-fixed-variant': '#3a485c',
        'primary-fixed-dim': '#bec6e0',
        'surface-container-high': '#e6e8ea',
        'on-secondary-fixed': '#0d1c2f',
        'tertiary-container': '#001f26',
        'on-tertiary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-tertiary-container': '#0090a9',
        'on-primary-fixed': '#131b2e',
        'secondary-fixed-dim': '#b9c7e0',
        'surface-tint': '#565e74',
        'on-primary': '#ffffff',
        'surface-container-highest': '#e0e3e5',
        'tertiary-fixed-dim': '#4cd7f6',
        'surface-bright': '#f7f9fb',
        'tertiary-fixed': '#acedff',
        'on-primary-container': '#7c839b',
        'on-surface-variant': '#45464d',
        'error': '#ba1a1a',
        'secondary-container': '#d5e3fd',
        'outline-variant': '#c6c6cd',
        'surface': '#f7f9fb',
        'on-surface': '#191c1e',
        'tertiary': '#000000',
        'inverse-surface': '#2d3133',
        'on-tertiary-fixed-variant': '#004e5c',
        'background': '#f7f9fb',
        'surface-container-low': '#f2f4f6',
        'technical-cyan': '#06B6D4',
        'navy-primary': '#0F172A',
        'cyan-tech': '#06B6D4',
        'navy-tech': '#0F172A',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        base: '4px',
        lg: '24px',
        'container-max': '1280px',
        xl: '48px',
        gutter: '24px',
        sm: '8px',
        xs: '4px',
        '2xl': '80px',
        md: '16px',
      },
      fontFamily: {
        'body-sm': ['Inter', 'sans-serif'],
        'display-lg-mobile': ['Geist', 'sans-serif'],
        'display-lg': ['Geist', 'sans-serif'],
        'headline-sm': ['Geist', 'sans-serif'],
        'label-md': ['Geist', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'mono-utility': ['Geist', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-md': ['Geist', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'mono-utility': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['30px', { lineHeight: '38px', letterSpacing: '-0.01em', fontWeight: '600' }],
      },
    },
  },
}